###php.ini
- name: upd_php_ini post_max_size
  lineinfile:
    dest: /etc/php.ini
    regexp: 'post_max_size ='
    line: 'post_max_size = 64M'
    state: present

- name: upd_php_ini memory_limit
  lineinfile:
    dest: /etc/php.ini
    regexp: 'memory_limit ='
    line: 'memory_limit = 256M'
    state: present

- name: upd_php_ini max_execution_time
  lineinfile:
    dest: /etc/php.ini
    regexp: 'max_execution_time ='
    line: 'max_execution_time = 300'
    state: present

- name: upd_php_ini upload_max_filesize
  lineinfile:
    dest: /etc/php.ini
    regexp: 'upload_max_filesize ='
    line: 'upload_max_filesize = 32M'
    state: present

- name: upd_php_ini date.timezone
  lineinfile:
    dest: /etc/php.ini
    regexp: ';date.timezone ='
    line: 'date.timezone = Europe/Moscow'
    state: present

###www.conf
- name: change wwwconf user
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: 'user ='
    line: 'user = nginx'
    state: present

- name: change wwwconf group
  lineinfile:
    dest: /etc/php-fpm.d/www.conf
    regexp: 'group ='
    line: 'group = nginx'
    state: present
###end

- name: restart php-fpm
  systemd:
    name: php-fpm
    enabled: true
    state: restarted
